fylein/fyle-qbo-api

apps/fyle/tasks.py
apps/workspaces/tasks.py
scripts/004-task-cleanup.sql

- Updated expense group creation method to either update previously created objects in import or create new only if it doesn't exist.
- Wrote a script to delete redundant entries in the database.

Clean up tasks on exports polling

---

.gitignore
apps/quickbooks_online/models.py

Change top level description for Single Expense

---

apps/quickbooks_online/models.py
apps/quickbooks_online/utils.py

* Changing Date to Spent At
* Add Expense Number in Document Number

BugFixes: Map Merchant to Vendor

---

apps/quickbooks_online/utils.py

This reverts commit af94b098128e553241de2695d692ea5fbdcd5099.

Revert "bug fix for syncing chart of account while onboarding (#163)"

---

apps/users/views.py

Change api/user/orgs response to just count instead of returning the whole json body

---

apps/workspaces/apis/map_employees/serializers.py
apps/workspaces/apis/map_employees/triggers.py
apps/workspaces/apis/map_employees/views.py
apps/workspaces/apis/urls.py

Here is the JSON Payload for the API `/api/v2/workspaces/2/map_employees/`
```json
{
"employee_field_mapping": "EMPLOYEE",
"auto_map_employees": "EMAIL"
}
```
JSON Response for THE API
```json
{
"employee_field_mapping": "EMPLOYEE",
"auto_map_employees": "EMAIL",
"workspace_id": 2
}
```

Map Employees API QBO Revamp

---

apps/fyle/views.py

API - 
`http://localhost:8000/api/workspaces/2/fyle/expense_groups/?expense_group_ids=51,50`

GET expense_groups by ID

---

apps/workspaces/apis/import_settings/triggers.py

add department grouping for both reimbursable and ccc expense_group fields without checking if reimbursable / ccc exports are enabled or not

---

apps/quickbooks_online/urls.py
apps/quickbooks_online/views.py
tests/test_quickbooks_online/test_views.py

This reverts commit 3069eff5909f3c5bd64b8e4fe969f999643f353e.

Revert "Generic mapping and employee mapping API changes commite (#337)"

---

apps/quickbooks_online/tasks.py
apps/quickbooks_online/utils.py

Fix for https://fylein.slack.com/archives/C01C6T9NFDK/p1675136647526439

Handle QBO disconnect during export

---

apps/quickbooks_online/utils.py
fyle_qbo_api/settings.py

Log exports payload

---

apps/workspaces/tasks.py
apps/workspaces/utils.py
fyle_qbo_api/tests/settings.py
requirements.txt

Added sendgrid-sdk for email notifications

---

apps/fyle/helpers.py
apps/fyle/views.py
tests/test_fyle/test_views.py

This reverts commit 72c3e29efb95369b565f789dbceb91222b2a864a.

Revert "Advance search for QBO (#563)"

---

requirements.txt

Fix activity mapping stats
[Handle Mappings for Activity Category](https://app.clickup.com/t/86cwkgp4t)

fix: activity mappings stats

---

requirements.txt

bump sdk version
http://app.clickup.com

chore: bump sdk version

---

apps/quickbooks_online/utils.py

fix: handle tax and amount being same
https://app.clickup.com/t/86cxmgtmc

fix: handle tax and amount being same

---

apps/fyle/helpers.py
apps/workspaces/actions.py

fix: get access token
https://app.clickup.com/

fix: get access token

---

.github/workflows/pytest.yml
apps/quickbooks_online/utils.py

fix: account sync
https://app.clickup.com/

fix: account sync

---

apps/internal/migrations/0001_auto_generated_sql.py

Please add PR description here, add screenshots if needed
https://app.clickup.com/

chore: fix new setup migration

---

requirements.txt
workers/actions.py
workers/worker.py

feat: add method for masking sensitive payload
